name: 'Create release of Python package'

description: 'Create a release and upload built python package to PyPI.'

inputs:
  pypi-package-name:
    description: 'Specify the name of the python package on PyPI.org.'
    required: true
    default: 'not-a-name'
  release-heading:
    description: 'Specify the heading for the release.'
    required: false
    default: '${{ github.ref_name }}'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ inputs.release-heading }}" \
              --generate-notes
    - name: Send event
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: release-created
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "release_id": "${{ steps.create_release.outputs.id }}", "pypi_package_name": "${{ inputs.pypi-package-name }}"}'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build
    - name: Build
      id: build
      shell: bash
      run: |
        python --version
        python -m build . --wheel
        echo "dist content:"
        ls dist/
    - name: Publish package distributions to PyPI
      env:
        name: pypi
        url: https://pypi.org/p/${{ inputs.pypi-package-name }}
      uses: pypa/gh-action-pypi-publish@release/v1
