name: 'Create release of Python package'

description: 'Create a release and upload built python package to PyPI.'

inputs:
  release-repository:
    description: 'Specify the repository where releases are made from.'
    required: true
    default: 'empty/nowhere'
  pypi-package-name:
    description: 'Specify the name of the python package on PyPI.org.'
    required: true
    default: 'not-a-name'
  github-token:
    description: 'Specify the GitHub token with contents and id-token write permission.'
    required: true
    default: '&&&'
  release-heading:
    description: 'Specify the heading for the release.'
    required: false
    default: '${{ github.ref }}'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"
    - name: Create Release
      id: create_release
      uses: KaiWedekind/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ inputs.release-heading }}
    - name: Send event
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: release-created
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "release_id": "${{ steps.create_release.outputs.id }}", "pypi_package_name": "${{ inputs.pypi-package-name }}"}'
