name: Changelog

on:
  repository_dispatch:
    types: [release-created]

jobs:
  changelog:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: "Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add changelog to release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.client_payload.release_id }}
          files: "CHANGELOG.md"
