name: Build and deploy library

on:
  repository_dispatch:
    types: [release-created]

jobs:
  build-package:
    runs-on: ubuntu-20.04
    name: Build and publish library package
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.client_payload.pypi_package_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
      - name: Build
        id: build
        run: |
          python --version
          python -m build . --wheel
          echo "dist content:"
          ls dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
